spring:
  datasource:
    url: "databaseurl"
    username: ""
    password: ""
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9193


